{
 "title": "Speech Inference Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Request Count",
   "type": "timeseries",
   "description": "Displays a time series graph showing the count of requests made to the speech inference endpoint over time. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(request_count_total[$__rate_interval])",
     "legendFormat": "Request Count"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, sum by(path, method)(rate(request_processing_seconds_bucket[20s]))) > 0.001",
     "legendFormat": "Request Duration"
    }
   ]
  },
  { "title": "Speech Inference API Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Percentage of Failed Requests",
   "type": "gauge",
   "description": "Percentage of Failed Requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * app_errors_total / (app_successful_requests_total + app_errors_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of Successful Requests",
   "type": "gauge",
   "description": "Percentage of Successful Requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * app_successful_requests_total / (app_successful_requests_total + app_errors_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}