name: Publish Python distribution to PyPI on Release

on:
  release:
    types: [published]

jobs:
  publish-to-pypi:
    name: Publish Python distribution to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/africanwhisper  

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: africanwhisper-package-distribution
          path: africanwhisper-package-distribution

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Extract tag name
        id: extract_tag
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

      - name: Set version in setup.cfg
        run: sed -i "s|version =.*|version = ${{ steps.extract_tag.outputs.tag }}/g" setup.cfg

      - name: Publish distribution 📦 to PyPI
        run: |
          python3 -m pip install twine
          python3 -m twine upload --repository pypi --username keviinkibe --password ${{ secrets.PYPI_API_TOKEN }} africanwhisper-package-distribution/*
