name: Test training.model_trainer Module.

on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt --no-cache-dir
          pip install pytest einops lion-pytorch

      - name: Install FFmpeg
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install FFmpeg (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install ffmpeg

      - name: Install FFmpeg (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          choco install ffmpeg

      - name: Run tests
        env:
          HF_READ_TOKEN: ${{ secrets.HF_READ_TOKEN }}
          HF_WRITE_TOKEN: ${{ secrets.HF_WRITE_TOKEN }}
          WANDB_TOKEN: ${{ secrets.WANDB_TOKEN }}
        run: pytest src/tests/test_model_trainer.py