name: Test training.model_trainer Module command on CPU

on: [pull_request]

jobs:
  unit-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Execute Trainer Command
        uses: KevKibe/kaggle-script-action@v1.0.5
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        with:
          username: ${{ secrets.KAGGLE_USERNAME }}
          key: ${{ secrets.KAGGLE_KEY }}
          title: "Test Trainer Command"
          custom_script: |
            cd src && python3 -m training.main --huggingface_token ${{ secrets.HF_TOKEN }}  --dataset_name mozilla-foundation/common_voice_16_1 --train_num_samples 10 --test_num_samples 10 --language_abbr af --model_id openai/whisper-tiny --processing_task transcribe --report_to wandb --wandb_api_key ${{ secrets.WANDB_TOKEN }} --max_steps 15 --train_batch_size 4 --eval_batch_size 4 --save_eval_logging_steps 10
          enable_internet: true
          enable_gpu: true
          enable_tpu: false
          sleep_time: 120

